//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/CCC/Inputs/CameraInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @CameraInputs: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @CameraInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""CameraInputs"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""2e4cd618-1105-46a6-8b74-031782f1e157"",
            ""actions"": [
                {
                    ""name"": ""Forward"",
                    ""type"": ""Value"",
                    ""id"": ""775533b4-400f-4705-8a6f-5d583bef80b2"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ForwardArrow"",
                    ""type"": ""Button"",
                    ""id"": ""1116badc-c0a7-4f2e-a92e-95bded9b6764"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Backward"",
                    ""type"": ""Value"",
                    ""id"": ""d3463f3c-c732-4769-91a5-cc8d1fe30819"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""BackwardArrow"",
                    ""type"": ""Value"",
                    ""id"": ""11edc893-be4a-4b2a-93e1-2a194c4bf422"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Left"",
                    ""type"": ""Value"",
                    ""id"": ""e610e18a-4baa-4244-af31-63a03d56c6ea"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftArrow"",
                    ""type"": ""Value"",
                    ""id"": ""15452fdd-9c65-48a9-80ed-1a7f5879c8de"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Right"",
                    ""type"": ""Value"",
                    ""id"": ""edbcb4d9-44a8-45d0-896f-4a8618f7a6f5"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightArrow"",
                    ""type"": ""Value"",
                    ""id"": ""b09efc04-ef6e-402c-9f07-ea29841ce314"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RotateLeft"",
                    ""type"": ""Value"",
                    ""id"": ""00408299-b858-4c5f-a39d-b6a0851c52e9"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RotateLeft_2"",
                    ""type"": ""Value"",
                    ""id"": ""22f94b82-151e-4358-889b-2dfe6c3b79b7"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RotateRight"",
                    ""type"": ""Value"",
                    ""id"": ""1405165e-308c-4b9a-90fa-fbce6be4178d"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RotateRight_2"",
                    ""type"": ""Value"",
                    ""id"": ""c7429ffe-c656-4fe1-b291-f457fbb96cad"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""bfbc932f-c46d-490a-b51e-66f0c669a857"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact_2"",
                    ""type"": ""Button"",
                    ""id"": ""94516975-5295-4318-995d-10c07ede6b85"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Zoom"",
                    ""type"": ""Value"",
                    ""id"": ""91cd76c2-0f61-4754-8004-05eefed16f64"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""fd38a889-565f-490f-9368-454bced68780"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select_2"",
                    ""type"": ""Button"",
                    ""id"": ""0bb761c8-4ae1-4f36-842f-c991c6e5a264"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""29365592-8ac9-4a99-9c99-2317ae37dd80"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause_2"",
                    ""type"": ""Button"",
                    ""id"": ""afc48bec-8c42-4ed3-9f76-25f6470430f0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Wheel"",
                    ""type"": ""Button"",
                    ""id"": ""6b42e52f-bf5c-4133-a861-e44fd5fe024a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Wheel_2"",
                    ""type"": ""Button"",
                    ""id"": ""fb14b230-1fae-411c-9a23-3e270e5da1eb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Map"",
                    ""type"": ""Button"",
                    ""id"": ""9de2c2a9-4e57-49a1-b419-c63269ef042a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Map_2"",
                    ""type"": ""Button"",
                    ""id"": ""24b4d2b3-18bf-4b3a-827c-a5b01e99e7c4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7676fbd2-a50a-4099-b779-5998329efe53"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""139fd108-3ef4-4cd0-a581-48ecd7c10a69"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""8be2409f-73a8-469f-a17b-404e33660bc4"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""66ca7a25-ae51-4562-a3ff-06b709076817"",
                    ""path"": ""<Mouse>/scroll/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""6ac18430-1d6a-494c-bb81-311f1e22279a"",
                    ""path"": ""<Mouse>/scroll/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""57031976-c817-4673-a37d-3f46337f463a"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f6c35aae-f062-4368-916e-ac00b2bf8daf"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Forward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""200e21f3-778d-4b22-be97-7babbce4e4ff"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Backward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3c996485-4ec3-443c-ad66-33243010f362"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a5889bbf-0bc8-4107-941e-da9d56544b5d"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""831c6fab-499a-4616-a7e8-b9eb785764c4"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e6d6639d-cec6-4cb5-81d5-ae07530434d7"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c7deef3b-7956-4903-9c71-5c1dc76ca27b"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ForwardArrow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f65f9a97-f1fe-42b7-b773-f2145eacaf96"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BackwardArrow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aaa9563a-f362-44b3-8858-77698904dcea"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftArrow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fa1d29b6-e4d1-46d2-96c2-d89de4d6189e"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightArrow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""86ba6412-a697-4e5c-81f5-5d0863110937"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateLeft_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2e5e16a4-43a2-4b91-a3e4-e984559c6c95"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateRight_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cf252373-7c16-4eaa-bdec-ec64d9fc1581"",
                    ""path"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dd769261-d910-4aa7-9288-05076370352b"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""baee6371-2b86-499b-9cde-fdf34c5776f0"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""496c3b16-8294-4929-8ccc-c63ebe3f7ec3"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Wheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""304985a2-fa15-4d01-b835-53e8b93d10fc"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Wheel_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""211e7d34-44c1-42d9-8215-cf0a70999235"",
                    ""path"": ""<Keyboard>/semicolon"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Map"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""596a0d76-dbd1-4089-ba58-34a644cd6d66"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Map_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Forward = m_Player.FindAction("Forward", throwIfNotFound: true);
        m_Player_ForwardArrow = m_Player.FindAction("ForwardArrow", throwIfNotFound: true);
        m_Player_Backward = m_Player.FindAction("Backward", throwIfNotFound: true);
        m_Player_BackwardArrow = m_Player.FindAction("BackwardArrow", throwIfNotFound: true);
        m_Player_Left = m_Player.FindAction("Left", throwIfNotFound: true);
        m_Player_LeftArrow = m_Player.FindAction("LeftArrow", throwIfNotFound: true);
        m_Player_Right = m_Player.FindAction("Right", throwIfNotFound: true);
        m_Player_RightArrow = m_Player.FindAction("RightArrow", throwIfNotFound: true);
        m_Player_RotateLeft = m_Player.FindAction("RotateLeft", throwIfNotFound: true);
        m_Player_RotateLeft_2 = m_Player.FindAction("RotateLeft_2", throwIfNotFound: true);
        m_Player_RotateRight = m_Player.FindAction("RotateRight", throwIfNotFound: true);
        m_Player_RotateRight_2 = m_Player.FindAction("RotateRight_2", throwIfNotFound: true);
        m_Player_Interact = m_Player.FindAction("Interact", throwIfNotFound: true);
        m_Player_Interact_2 = m_Player.FindAction("Interact_2", throwIfNotFound: true);
        m_Player_Zoom = m_Player.FindAction("Zoom", throwIfNotFound: true);
        m_Player_Select = m_Player.FindAction("Select", throwIfNotFound: true);
        m_Player_Select_2 = m_Player.FindAction("Select_2", throwIfNotFound: true);
        m_Player_Pause = m_Player.FindAction("Pause", throwIfNotFound: true);
        m_Player_Pause_2 = m_Player.FindAction("Pause_2", throwIfNotFound: true);
        m_Player_Wheel = m_Player.FindAction("Wheel", throwIfNotFound: true);
        m_Player_Wheel_2 = m_Player.FindAction("Wheel_2", throwIfNotFound: true);
        m_Player_Map = m_Player.FindAction("Map", throwIfNotFound: true);
        m_Player_Map_2 = m_Player.FindAction("Map_2", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_Forward;
    private readonly InputAction m_Player_ForwardArrow;
    private readonly InputAction m_Player_Backward;
    private readonly InputAction m_Player_BackwardArrow;
    private readonly InputAction m_Player_Left;
    private readonly InputAction m_Player_LeftArrow;
    private readonly InputAction m_Player_Right;
    private readonly InputAction m_Player_RightArrow;
    private readonly InputAction m_Player_RotateLeft;
    private readonly InputAction m_Player_RotateLeft_2;
    private readonly InputAction m_Player_RotateRight;
    private readonly InputAction m_Player_RotateRight_2;
    private readonly InputAction m_Player_Interact;
    private readonly InputAction m_Player_Interact_2;
    private readonly InputAction m_Player_Zoom;
    private readonly InputAction m_Player_Select;
    private readonly InputAction m_Player_Select_2;
    private readonly InputAction m_Player_Pause;
    private readonly InputAction m_Player_Pause_2;
    private readonly InputAction m_Player_Wheel;
    private readonly InputAction m_Player_Wheel_2;
    private readonly InputAction m_Player_Map;
    private readonly InputAction m_Player_Map_2;
    public struct PlayerActions
    {
        private @CameraInputs m_Wrapper;
        public PlayerActions(@CameraInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Forward => m_Wrapper.m_Player_Forward;
        public InputAction @ForwardArrow => m_Wrapper.m_Player_ForwardArrow;
        public InputAction @Backward => m_Wrapper.m_Player_Backward;
        public InputAction @BackwardArrow => m_Wrapper.m_Player_BackwardArrow;
        public InputAction @Left => m_Wrapper.m_Player_Left;
        public InputAction @LeftArrow => m_Wrapper.m_Player_LeftArrow;
        public InputAction @Right => m_Wrapper.m_Player_Right;
        public InputAction @RightArrow => m_Wrapper.m_Player_RightArrow;
        public InputAction @RotateLeft => m_Wrapper.m_Player_RotateLeft;
        public InputAction @RotateLeft_2 => m_Wrapper.m_Player_RotateLeft_2;
        public InputAction @RotateRight => m_Wrapper.m_Player_RotateRight;
        public InputAction @RotateRight_2 => m_Wrapper.m_Player_RotateRight_2;
        public InputAction @Interact => m_Wrapper.m_Player_Interact;
        public InputAction @Interact_2 => m_Wrapper.m_Player_Interact_2;
        public InputAction @Zoom => m_Wrapper.m_Player_Zoom;
        public InputAction @Select => m_Wrapper.m_Player_Select;
        public InputAction @Select_2 => m_Wrapper.m_Player_Select_2;
        public InputAction @Pause => m_Wrapper.m_Player_Pause;
        public InputAction @Pause_2 => m_Wrapper.m_Player_Pause_2;
        public InputAction @Wheel => m_Wrapper.m_Player_Wheel;
        public InputAction @Wheel_2 => m_Wrapper.m_Player_Wheel_2;
        public InputAction @Map => m_Wrapper.m_Player_Map;
        public InputAction @Map_2 => m_Wrapper.m_Player_Map_2;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @Forward.started += instance.OnForward;
            @Forward.performed += instance.OnForward;
            @Forward.canceled += instance.OnForward;
            @ForwardArrow.started += instance.OnForwardArrow;
            @ForwardArrow.performed += instance.OnForwardArrow;
            @ForwardArrow.canceled += instance.OnForwardArrow;
            @Backward.started += instance.OnBackward;
            @Backward.performed += instance.OnBackward;
            @Backward.canceled += instance.OnBackward;
            @BackwardArrow.started += instance.OnBackwardArrow;
            @BackwardArrow.performed += instance.OnBackwardArrow;
            @BackwardArrow.canceled += instance.OnBackwardArrow;
            @Left.started += instance.OnLeft;
            @Left.performed += instance.OnLeft;
            @Left.canceled += instance.OnLeft;
            @LeftArrow.started += instance.OnLeftArrow;
            @LeftArrow.performed += instance.OnLeftArrow;
            @LeftArrow.canceled += instance.OnLeftArrow;
            @Right.started += instance.OnRight;
            @Right.performed += instance.OnRight;
            @Right.canceled += instance.OnRight;
            @RightArrow.started += instance.OnRightArrow;
            @RightArrow.performed += instance.OnRightArrow;
            @RightArrow.canceled += instance.OnRightArrow;
            @RotateLeft.started += instance.OnRotateLeft;
            @RotateLeft.performed += instance.OnRotateLeft;
            @RotateLeft.canceled += instance.OnRotateLeft;
            @RotateLeft_2.started += instance.OnRotateLeft_2;
            @RotateLeft_2.performed += instance.OnRotateLeft_2;
            @RotateLeft_2.canceled += instance.OnRotateLeft_2;
            @RotateRight.started += instance.OnRotateRight;
            @RotateRight.performed += instance.OnRotateRight;
            @RotateRight.canceled += instance.OnRotateRight;
            @RotateRight_2.started += instance.OnRotateRight_2;
            @RotateRight_2.performed += instance.OnRotateRight_2;
            @RotateRight_2.canceled += instance.OnRotateRight_2;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
            @Interact_2.started += instance.OnInteract_2;
            @Interact_2.performed += instance.OnInteract_2;
            @Interact_2.canceled += instance.OnInteract_2;
            @Zoom.started += instance.OnZoom;
            @Zoom.performed += instance.OnZoom;
            @Zoom.canceled += instance.OnZoom;
            @Select.started += instance.OnSelect;
            @Select.performed += instance.OnSelect;
            @Select.canceled += instance.OnSelect;
            @Select_2.started += instance.OnSelect_2;
            @Select_2.performed += instance.OnSelect_2;
            @Select_2.canceled += instance.OnSelect_2;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
            @Pause_2.started += instance.OnPause_2;
            @Pause_2.performed += instance.OnPause_2;
            @Pause_2.canceled += instance.OnPause_2;
            @Wheel.started += instance.OnWheel;
            @Wheel.performed += instance.OnWheel;
            @Wheel.canceled += instance.OnWheel;
            @Wheel_2.started += instance.OnWheel_2;
            @Wheel_2.performed += instance.OnWheel_2;
            @Wheel_2.canceled += instance.OnWheel_2;
            @Map.started += instance.OnMap;
            @Map.performed += instance.OnMap;
            @Map.canceled += instance.OnMap;
            @Map_2.started += instance.OnMap_2;
            @Map_2.performed += instance.OnMap_2;
            @Map_2.canceled += instance.OnMap_2;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @Forward.started -= instance.OnForward;
            @Forward.performed -= instance.OnForward;
            @Forward.canceled -= instance.OnForward;
            @ForwardArrow.started -= instance.OnForwardArrow;
            @ForwardArrow.performed -= instance.OnForwardArrow;
            @ForwardArrow.canceled -= instance.OnForwardArrow;
            @Backward.started -= instance.OnBackward;
            @Backward.performed -= instance.OnBackward;
            @Backward.canceled -= instance.OnBackward;
            @BackwardArrow.started -= instance.OnBackwardArrow;
            @BackwardArrow.performed -= instance.OnBackwardArrow;
            @BackwardArrow.canceled -= instance.OnBackwardArrow;
            @Left.started -= instance.OnLeft;
            @Left.performed -= instance.OnLeft;
            @Left.canceled -= instance.OnLeft;
            @LeftArrow.started -= instance.OnLeftArrow;
            @LeftArrow.performed -= instance.OnLeftArrow;
            @LeftArrow.canceled -= instance.OnLeftArrow;
            @Right.started -= instance.OnRight;
            @Right.performed -= instance.OnRight;
            @Right.canceled -= instance.OnRight;
            @RightArrow.started -= instance.OnRightArrow;
            @RightArrow.performed -= instance.OnRightArrow;
            @RightArrow.canceled -= instance.OnRightArrow;
            @RotateLeft.started -= instance.OnRotateLeft;
            @RotateLeft.performed -= instance.OnRotateLeft;
            @RotateLeft.canceled -= instance.OnRotateLeft;
            @RotateLeft_2.started -= instance.OnRotateLeft_2;
            @RotateLeft_2.performed -= instance.OnRotateLeft_2;
            @RotateLeft_2.canceled -= instance.OnRotateLeft_2;
            @RotateRight.started -= instance.OnRotateRight;
            @RotateRight.performed -= instance.OnRotateRight;
            @RotateRight.canceled -= instance.OnRotateRight;
            @RotateRight_2.started -= instance.OnRotateRight_2;
            @RotateRight_2.performed -= instance.OnRotateRight_2;
            @RotateRight_2.canceled -= instance.OnRotateRight_2;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
            @Interact_2.started -= instance.OnInteract_2;
            @Interact_2.performed -= instance.OnInteract_2;
            @Interact_2.canceled -= instance.OnInteract_2;
            @Zoom.started -= instance.OnZoom;
            @Zoom.performed -= instance.OnZoom;
            @Zoom.canceled -= instance.OnZoom;
            @Select.started -= instance.OnSelect;
            @Select.performed -= instance.OnSelect;
            @Select.canceled -= instance.OnSelect;
            @Select_2.started -= instance.OnSelect_2;
            @Select_2.performed -= instance.OnSelect_2;
            @Select_2.canceled -= instance.OnSelect_2;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
            @Pause_2.started -= instance.OnPause_2;
            @Pause_2.performed -= instance.OnPause_2;
            @Pause_2.canceled -= instance.OnPause_2;
            @Wheel.started -= instance.OnWheel;
            @Wheel.performed -= instance.OnWheel;
            @Wheel.canceled -= instance.OnWheel;
            @Wheel_2.started -= instance.OnWheel_2;
            @Wheel_2.performed -= instance.OnWheel_2;
            @Wheel_2.canceled -= instance.OnWheel_2;
            @Map.started -= instance.OnMap;
            @Map.performed -= instance.OnMap;
            @Map.canceled -= instance.OnMap;
            @Map_2.started -= instance.OnMap_2;
            @Map_2.performed -= instance.OnMap_2;
            @Map_2.canceled -= instance.OnMap_2;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnForward(InputAction.CallbackContext context);
        void OnForwardArrow(InputAction.CallbackContext context);
        void OnBackward(InputAction.CallbackContext context);
        void OnBackwardArrow(InputAction.CallbackContext context);
        void OnLeft(InputAction.CallbackContext context);
        void OnLeftArrow(InputAction.CallbackContext context);
        void OnRight(InputAction.CallbackContext context);
        void OnRightArrow(InputAction.CallbackContext context);
        void OnRotateLeft(InputAction.CallbackContext context);
        void OnRotateLeft_2(InputAction.CallbackContext context);
        void OnRotateRight(InputAction.CallbackContext context);
        void OnRotateRight_2(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnInteract_2(InputAction.CallbackContext context);
        void OnZoom(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
        void OnSelect_2(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnPause_2(InputAction.CallbackContext context);
        void OnWheel(InputAction.CallbackContext context);
        void OnWheel_2(InputAction.CallbackContext context);
        void OnMap(InputAction.CallbackContext context);
        void OnMap_2(InputAction.CallbackContext context);
    }
}
